name: build

on:
  push:
    branches: bh/ci
  pull_request:
    branches: bh/ci

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, ghc: ghc884 }
          - { os: ubuntu-latest, ghc: ghc8104 }
          - { os: macos-latest, ghc: ghc8104 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/

      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - if: ${{ matrix.os != 'macos-latest' }}
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt &

      - run: nix-build -A ci.library -A ci.checks --argstr ghcVersion ${{ matrix.ghc }}
